export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
<<<<<<< HEAD
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL";
=======
export const COURSE_CREATION_SUCCESS = "COURSE_CREATION_SUCCESS";
export const COURSE_CREATION_FAIL = "COURSE_CREATION_FAIL";
>>>>>>> c85b2bc4b901199ff14853ce947264702a4086c1
